//   Copyright 2026 William Isted and contributors
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

#pragma once

// Declaration of verb_specs(): the compile-time embedded spec corpus used by
// system.verbs.  Defined in agents/windows-modern/src/verbs_blob.cpp
// (AUTO-GENERATED by Tools/gen_verbs.py).  Only the windows-modern build
// compiles verbs_blob.cpp; other families define a fallback via #else in
// agents/shared/verbs/system.cpp and system.verbs is gated off for them.

#include <string_view>
#include <unordered_map>

namespace remote_hands::system_verbs {

// Full per-verb spec corpus (entire spec JSON). Backs the system.verbs verb.
const std::unordered_map<std::string_view, std::string_view>&
verb_specs() noexcept;

// Pre-sliced MCP tools/list fragments (PROTOCOL.md §1.6.2). The mapped value
// is the JSON text that follows `"name":"<verb>"` inside a tool object —
// i.e. `,"description":...,"inputSchema":...,"x-crudx":...,"x-tier":...`.
// Excludes the §1.6.7 verbs (connection.hello/close/reset, system.verbs).
// The MCP tools/list handler concatenates `{"name":"<v>"<fragment>}`.
const std::unordered_map<std::string_view, std::string_view>&
verb_tool_meta() noexcept;

}  // namespace remote_hands::system_verbs
