#!/usr/bin/env python3
"""Generate agents/windows-modern/src/verbs_blob.cpp from protocol spec JSON.

Reads every verb JSON file under protocol/spec/verbs/**/*.json, filters to
verbs whose x-families.windows-modern.implemented is not explicitly false, and
writes a C++ source file that embeds each spec as a raw-string literal.

The generated file is compiled only into the windows-modern build; it provides
system_verbs::verb_specs() which the system.verbs verb handler uses to return
the full spec corpus over the wire.

Usage:
    python Tools/gen_verbs.py
"""

import json
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).parent.parent
SPEC_DIR  = REPO_ROOT / "protocol" / "spec" / "verbs"
OUT_FILE  = REPO_ROOT / "agents" / "windows-modern" / "src" / "verbs_blob.cpp"


def is_modern_implemented(spec: dict) -> bool:
    """Return True unless x-families.windows-modern.implemented is False."""
    fams   = spec.get("x-families", {})
    modern = fams.get("windows-modern", {})
    return modern.get("implemented", True) is not False


def main() -> None:
    if not SPEC_DIR.is_dir():
        print(f"ERROR: spec directory not found: {SPEC_DIR}", file=sys.stderr)
        print("       Run 'git submodule update --init' first.", file=sys.stderr)
        sys.exit(1)

    specs: dict[str, str] = {}
    for path in sorted(SPEC_DIR.rglob("*.json")):
        try:
            with open(path, encoding="utf-8") as f:
                spec = json.load(f)
        except json.JSONDecodeError as e:
            print(f"WARNING: skipping {path}: {e}", file=sys.stderr)
            continue

        if not is_modern_implemented(spec):
            continue

        name = spec.get("name")
        if not name:
            print(f"WARNING: skipping {path}: no 'name' field", file=sys.stderr)
            continue

        # Re-serialise to compact JSON (no x-* stripping — clients that don't
        # recognise an x-* key MUST ignore it per spec §1.4).
        raw = json.dumps(spec, separators=(",", ":"), ensure_ascii=False)
        specs[name] = raw

    # Use )SPEC" as the raw-string terminator sentinel.  JSON content cannot
    # contain this sequence because ) is plain text and SPEC" would require an
    # unescaped double-quote mid-value.
    DELIM = "SPEC"

    lines: list[str] = [
        "// AUTO-GENERATED by Tools/gen_verbs.py — do not edit.",
        "// Source: protocol/spec/verbs/**/*.json filtered to windows-modern.",
        "// Regenerate: python Tools/gen_verbs.py",
        "",
        '#include "verbs_blob.hpp"',
        "",
        "#include <string_view>",
        "#include <unordered_map>",
        "",
        "namespace remote_hands::system_verbs {",
        "",
        "static const std::unordered_map<std::string_view, std::string_view> kVerbSpecs{",
    ]

    for name, raw in sorted(specs.items()):
        if f"){DELIM}\"" in raw:
            # Extremely unlikely; log and skip rather than producing bad C++.
            print(f"WARNING: {name}: raw JSON contains raw-string delimiter "
                  f"')SPEC\"' — skipped", file=sys.stderr)
            continue
        lines.append(f'    {{"{name}", R"{DELIM}({raw}){DELIM}"}},')

    lines += [
        "};",
        "",
        "const std::unordered_map<std::string_view, std::string_view>&",
        "verb_specs() noexcept { return kVerbSpecs; }",
        "",
        "}  // namespace remote_hands::system_verbs",
        "",
    ]

    OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"gen_verbs.py: wrote {len(specs)} verb specs to {OUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
